#!/usr/bin/env bash
# This Script connects to the server 100.25.33.252 using the users private key
# stored in a file school Found in the users home directory
ssh ubuntu@100.25.223.112 -i ~/.ssh/school
